services:
  # 1. เซิร์ฟเวอร์ฐานข้อมูล MariaDB
  fluoride_db:
    image: mariadb:10.11
    container_name: moph_mariadb
    restart: always
    environment:
      TZ: Asia/Bangkok
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-adminpassword}
      MYSQL_DATABASE: moph_fluoride_db
    # ปิด ports: สู่ภายนอกเพื่อความปลอดภัย
    volumes:
      - db_data:/var/lib/mysql

  # 2. เซิร์ฟเวอร์ phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: moph_phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      TZ: Asia/Bangkok
      PMA_HOST: fluoride_db
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-adminpassword}
    depends_on:
      - fluoride_db

  # 3. แอปพลิเคชัน Python (Flask)
  web_app:
    build: .
    container_name: moph_webapp
    restart: always
    ports:
      - "5000:5000" # เข้าถึงเว็บผ่านพอร์ต 5000
    environment:
      TZ: Asia/Bangkok
      DB_USER: root
      DB_PASSWORD: ${DB_PASSWORD:-adminpassword}
      DB_HOST: fluoride_db
      DB_PORT: 3306
      DB_NAME: moph_fluoride_db
      ADMIN_PASSWORD: ${ADMIN_PASSWORD:-admin}
    depends_on:
      - fluoride_db # รอให้ DB รันเสร็จก่อนค่อยรัน Web App

volumes:
  db_data: