services:
  fluoride_db:
    image: mariadb:10.11
    container_name: moph_mariadb_dev
    restart: always
    environment:
      TZ: Asia/Bangkok
      MYSQL_ROOT_PASSWORD: adminpassword
      MYSQL_DATABASE: moph_fluoride_db
    ports:
      - "3306:3306"
    volumes:
      - db_data_dev:/var/lib/mysql

  web_app:
    build: .
    command: python app.py
    container_name: moph_webapp_dev
    restart: always
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    environment:
      TZ: Asia/Bangkok
      DB_USER: root
      DB_PASSWORD: adminpassword
      DB_HOST: fluoride_db
      DB_PORT: 3306
      DB_NAME: moph_fluoride_db
      ADMIN_PASSWORD: admin
      FLASK_DEBUG: 1
    depends_on:
      - fluoride_db

volumes:
  db_data_dev:

